export const dynamic = 'force-dynamic';
import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

interface BrandData {
  clientName: string;
  slug: string;
  websiteUrl: string;
  industry?: string;
  city?: string;
  state?: string;
  services?: string[];
  tagline?: string;
  targetAudience?: string;
  designPreferences?: {
    colors?: string[];
    style?: string;
    competitors?: string[];
  };
  contact?: {
    phone?: string;
    email?: string;
    address?: string;
  };
}

export async function POST(request: Request) {
  try {
    const body: BrandData = await request.json();
    const { 
      clientName, 
      slug, 
      websiteUrl, 
      industry, 
      city, 
      state, 
      services, 
      tagline,
      targetAudience,
      designPreferences,
      contact 
    } = body;

    if (!clientName || !slug) {
      return NextResponse.json({ error: 'clientName and slug are required' }, { status: 400 });
    }

    // Generate SPEC.md content
    const specContent = `# ${clientName} - Website Specification

## Project Overview
- **Client**: ${clientName}
- **Project Type**: Website Build
- **Industry**: ${industry || 'Trade Services'}
- **Location**: ${city || ''}, ${state || ''}
- **Website**: ${websiteUrl || 'N/A'}
- **Generated**: ${new Date().toISOString().split('T')[0]}

## Business Profile
${tagline ? `- **Tagline**: ${tagline}` : ''}
${targetAudience ? `- **Target Audience**: ${targetAudience}` : ''}
${services?.length ? `- **Services**: ${services.join(', ')}` : ''}

${contact ? `## Contact Information
${contact.phone ? `- **Phone**: ${contact.phone}` : ''}
${contact.email ? `- **Email**: ${contact.email}` : ''}
${contact.address ? `- **Address**: ${contact.address}` : ''}
` : ''}

## Design Preferences
${designPreferences?.colors?.length ? `- **Colors**: ${designPreferences.colors.join(', ')}` : '- **Colors**: To be determined'}
${designPreferences?.style ? `- **Style**: ${designPreferences.style}` : '- **Style**: Professional, modern'}

## Competitors
${designPreferences?.competitors?.length ? designPreferences.competitors.map(c => `- ${c}`).join('\n') : '- TBD based on research'}

## Scope of Work

### Phase 1: Foundation
- [ ] Professional homepage with hero section
- [ ] Services page
- [ ] About/Company page
- [ ] Contact page with lead capture

### Phase 2: Features
- [ ] Mobile-responsive design
- [ ] Lead generation forms
- [ ] Call-to-action optimization
- [ ] Basic SEO setup

### Phase 3: Polish
- [ ] Performance optimization
- [ ] Cross-browser testing
- [ ] Final revisions

## Timeline
- **Phase 1**: Week 1
- **Phase 2**: Week 2
- **Phase 3**: Week 3

## Notes
Generated by Athena SPEC.md Generator
`;

    // Save to projects folder
    const projectsDir = path.join(process.env.HOME || '/Users/jaivienkendrick', 'projects', 'client-sites', slug);
    
    // Create directory if it doesn't exist
    if (!fs.existsSync(projectsDir)) {
      fs.mkdirSync(projectsDir, { recursive: true });
    }

    const specPath = path.join(projectsDir, 'SPEC.md');
    fs.writeFileSync(specPath, specContent);

    return NextResponse.json({
      success: true,
      slug,
      specPath,
      message: `SPEC.md generated for ${clientName}`
    });

  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
